title: NLPLAB
description: SKK Univ. NLP LAB.
url: "https://hecarimday.github.io"
baseurl: ""

pagination:
  enabled: true
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  index_page_name: 'index.html'
  
markdown: kramdown
highlighter: rouge

# [수정] gems 대신 최신 규격인 plugins 하나만 사용하세요. 
plugins:
  - jekyll-paginate-v2

navigation:
  - title: Home
    url: /index.html
  - title: About Us
    url: /AboutUs/Introduction/
  - title: Research
    url: /Research/Fields/
  - title: Publications
    url: /Publications/JournalPapers/
  - title: Members
    url: /Members/
  - title: Demos
    url: /Demos/Natural_Language_Processing/
  - title: Boards
    url: /Boards/notice/
  - title: Links
    url: /Boards/link/

social:
  github: "https://github.com/NLPlab-skku"
  linkedin: "https://www.linkedin.com/company/skku-nlplab/posts/?feedView=all"
  apply: "https://forms.gle/bdW4K2uYqvteRWfX7"
  email: nlplab.skku@gmail.com

google_analytics: "UA-58263416-1"

# 빌드 시 불필요한 파일 제외 (속도 향상)
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .jekyll-cache