backend:
  name: github
  repo: hecarimday/hecarimday.github.io
  branch: main
  # [핵심] 네트리파이 주소를 베이스로 잡아야 팝업창이 안 터집니다.
  base_url: https://sweet-genie-b1cd1b.netlify.app
  # [핵심] 아까 복사한 API ID를 여기에 한 번 더 박아줍니다.
  site_id: 05fba26d-e0c1-4cf6-b175-354d90f7d367

# 이하 게시판 설정 (기존 것 유지)
collections:
  - name: "notice"
    label: "Notice"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }