backend:
  name: github
  repo: hecarimday/hecarimday.github.io # 예: hecarimday/hecarimday.github.io
  branch: main # 혹은 master

media_folder: "assets/img" # 사진이 저장될 경로
public_folder: "/assets/img" # 웹사이트에서 사진을 불러올 경로

collections:
  - name: "notice" # 컬렉션 이름
    label: "Notice" # 화면에 표시될 이름
    folder: "_posts" # 글이 저장되는 폴더
    create: true # 새 글 쓰기 허용 여부
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # 파일명 규칙
    fields: # 글쓰기 창에 나타날 입력칸들
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string", default: "Admin" }
      - { label: "Category", name: "category", widget: "hidden", default: "notice" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }