# 1. 백엔드 설정 (인증 관련)
backend:
  name: git-gateway
  repo: hecarimday/hecarimday.github.io
  branch: main
  base_url: https://sweet-genie-b1cd1b.netlify.app
  site_id: 05fba26d-e0c1-4cf6-b175-354d90f7d367

# 2. 미디어 설정 (에러의 원인이었던 필수값들!)
# 글 쓸 때 업로드하는 사진들이 저장될 경로입니다.
media_folder: "assets/images/posts"
public_folder: "/assets/images/posts"

# 3. 게시판(Notice) 설정
collections:
  - name: "notice"
    label: "Notice"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }